resources:
  pipelines:
    product_silver:
      name: product_silver
      libraries:
        - glob:
            include: ../../../src/product/product_silver/transformations/**
        - glob:
            include: ../../../src/manufacturer/**
      serverless: true
      catalog: dev
      schema: 02_silver
      root_path: ../../../src/product/product_silver

