resources:
  pipelines:
    product_silver:
      name: product_silver
      libraries:
        - glob:
            include: ../../../src/product/product_silver/transformations/**
      serverless: true
      catalog: ${var.catalog}
      schema: ${var.bronze}
      root_path: ../../../src/product/product_silver
      configuration:
        catalog: ${var.catalog}
        target_schema: ${var.silver}

